### ISSUE TITLE
when I run first example, got error infomations like that, how should I do? Any help would be greatly appreciated.

### ISSUE THREAD

**Issue by HuLiangHu** [JackMcKew/pandas_alive#24]
MovieWriter imagemagick unavailable; using Pillow instead.
Traceback (most recent call last):
  File "C:\Users\aaron.hu\Anaconda\lib\site-packages\matplotlib\animation.py", line 251, in saving
    yield self
  File "C:\Users\aaron.hu\Anaconda\lib\site-packages\matplotlib\animation.py", line 1137, in save
    writer.grab_frame(**savefig_kwargs)
  File "C:\Users\aaron.hu\Anaconda\lib\site-packages\matplotlib\animation.py", line 548, in grab_frame
    renderer = self.fig.canvas.get_renderer()
AttributeError: 'FigureCanvasBase' object has no attribute 'get_renderer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/aaron.hu/PycharmProjects/appsCrawler.py", line 7, in <module>
    df.plot_animated(filename='examples/example-barh-chart.gif')
  File "C:\Users\aaron.hu\Anaconda\lib\site-packages\pandas_alive\plotting.py", line 606, in __call__
    return plot(self.df, *args, **kwargs)
  File "C:\Users\aaron.hu\Anaconda\lib\site-packages\pandas_alive\plotting.py", line 312, in plot
    bcr.save(verify_filename(filename))
  File "C:\Users\aaron.hu\Anaconda\lib\site-packages\pandas_alive\_base_chart.py", line 567, in save
    filename, fps=self.fps, dpi=self.dpi, writer="imagemagick"
  File "C:\Users\aaron.hu\Anaconda\lib\site-packages\matplotlib\animation.py", line 1137, in save
    writer.grab_frame(**savefig_kwargs)
  File "C:\Users\aaron.hu\Anaconda\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\aaron.hu\Anaconda\lib\site-packages\matplotlib\animation.py", line 253, in saving
    self.finish()
  File "C:\Users\aaron.hu\Anaconda\lib\site-packages\matplotlib\animation.py", line 553, in finish
    self._frames[0].save(
IndexError: list index out of range

**Comment by JackMcKew** [comment]
I believe this has something to do with the backends that the package is trying to use, would you mind sharing how you installed `pandas-alive`

**Comment by JackMcKew** [comment]
Closing due to no update

**Comment by ethanlchristensen** [comment]
Adding comment:
- I can run the base example, but if I change to `kind="line"` I get the same error HuLiangHu mentioned.
