### ISSUE TITLE
urllib.error.HTTPERROR: HTTP ERROR 404: Not Found

### ISSUE THREAD

**Issue by HeMauro** [JackMcKew/pandas_alive#35]
When i try to run the first example i get this error message:

/home/mauro/Documentos/chart-race-cometa/env/bin/python /home/mauro/Documentos/chart-race-cometa/main.py
Traceback (most recent call last):
  File "/home/mauro/Documentos/chart-race-cometa/main.py", line 4, in <module>
    df = pd.load_dataset('data/covid19.csv')
  File "/home/mauro/Documentos/chart-race-cometa/env/lib/python3.8/site-packages/pandas_alive/base.py", line 28, in load_dataset
    return pd.read_csv(
  File "/home/mauro/Documentos/chart-race-cometa/env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/mauro/Documentos/chart-race-cometa/env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/mauro/Documentos/chart-race-cometa/env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/mauro/Documentos/chart-race-cometa/env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/mauro/Documentos/chart-race-cometa/env/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/mauro/Documentos/chart-race-cometa/env/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/mauro/Documentos/chart-race-cometa/env/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/home/mauro/Documentos/chart-race-cometa/env/lib/python3.8/site-packages/pandas/io/common.py", line 608, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "/home/mauro/Documentos/chart-race-cometa/env/lib/python3.8/site-packages/pandas/io/common.py", line 311, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "/home/mauro/Documentos/chart-race-cometa/env/lib/python3.8/site-packages/pandas/io/common.py", line 211, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Any ideia of what it could be?

**Comment by JackMcKew** [comment]
Does this still occur?
